server.port=9916
spring.application.name=spring-boot-redis

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=${mysql.datasource.url}
spring.datasource.username=${mysql.datasource.username}
spring.datasource.password=${mysql.datasource.password}

#### redis start
# 单机部署
spring.redission.host=${spring.redis.simple.host}
spring.redission.port=${spring.redis.simple.port}
#### end

# 缓存类型
spring.cache.type=redis