## mysql’À∫≈√‹¬Î
mysql.datasource.url=jdbc:mysql://localhost:3306/neil_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
mysql.datasource.username=root
mysql.datasource.password=root
## Oracle’À∫≈√‹¬Î
oracle.datasource.url=jdbc:oracle:thin:@10.45.50.175:1521/mexprov
oracle.datasource.username=oss_isap
oracle.datasource.password=mexprov2021
## redis’À∫≈√‹¬Î
spring.redis.simple.host=192.168.129.128
spring.redis.simple.port=6379
spring.redis.simple.password=root
spring.redis.cluster.nodes.ip=192.168.129.128
spring.redis.cluster.hosts=192.168.129.128:7010,192.168.129.128:7020,192.168.129.128:7030,192.168.129.128:7011,192.168.129.128:7021,192.168.129.128:7031
spring.redis.cluster.password=
## rocketMQ
rocket.mq.namesrvAddr=192.168.129.128:9876