-- ----------------------------
-- Table structure for TEST_TABLE
-- ----------------------------
-- DROP TABLE TEST_TABLE;
CREATE TABLE TEST_TABLE (
  ID NUMBER(16) VISIBLE NOT NULL ,
  ACTION VARCHAR2(500 BYTE) VISIBLE DEFAULT NULL ,
  NAME VARCHAR2(500 BYTE) VISIBLE DEFAULT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
alter table test_table add primary key (ID);

-- ----------------------------
-- Records of TEST_TABLE
-- ----------------------------
INSERT INTO test_table VALUES (1, 'get', 'getName');
INSERT INTO test_table VALUES (2, 'post', 'getType');
INSERT INTO test_table VALUES (5383, 'tableaction', 'tableName');
INSERT INTO test_table VALUES (6499, 'tableaction', 'tableName');
INSERT INTO test_table VALUES (8165, 'tableaction', 'tableName');

-- ----------------------------
-- Table structure for WO_ORDER_STATE
-- ----------------------------
-- DROP TABLE "OSS_ISAP"."WO_ORDER_STATE";
CREATE TABLE "OSS_ISAP"."WO_ORDER_STATE" (
  "NAME" VARCHAR2(128 BYTE) VISIBLE ,
  "STATE_CODE" VARCHAR2(24 BYTE) VISIBLE NOT NULL
)
  LOGGING
  NOCOMPRESS
  PCTFREE 10
  INITRANS 1
  STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
          )
  PARALLEL 1
  NOCACHE
  DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of WO_ORDER_STATE
-- ----------------------------
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('MANUAL HANDLING', '101');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('ROLLING BACK', '10C');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('EXECUTING', '10D');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('EXCEPTION', '10E');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('FINISH EXECUTE SUCCESS', '10F');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RECEIPT FOR OUT SYSTEM FAIL', '10FM');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('FINISH - WAITING FOR DUMPING', '10FX');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('NOT STARTED', '10I');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('SKIP', '10J');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RECEIPT FAIL', '10M');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('ORIGINAL ROLLBACK', '10R');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RETURN-ROLLBACK FAIL', '10RE');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RETURN-ROLLBACK SUCCESS', '10RF');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RETURN-ROLLBACK SUCCESS(WAITING FOR DUMPING)', '10RFX');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('FINISH - NO INSTRUCTION', '10S');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('NO INSTRUCTION EXCEPTION', '10SE');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('FINISH - NO INSTRUCTION(WAITING FOR DUMPING)', '10SX');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RECEIPT COMPLETE', '10T');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RECEIPT COMPLETE(WAITING FOR DUMPING)', '10TX');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('RECEIPT EXCEPTION', '10U');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('ABOLISH', '10V');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('INITIALIZE EXCUTION', '14I');
INSERT INTO "OSS_ISAP"."WO_ORDER_STATE" VALUES ('KICK-OFF', '10K');

-- ----------------------------
-- Primary Key structure for table WO_ORDER_STATE
-- ----------------------------
ALTER TABLE "OSS_ISAP"."WO_ORDER_STATE" ADD CONSTRAINT "WO_ORDER_STATE_PRIMARY_KEY" PRIMARY KEY ("STATE_CODE");